### PR TITLE
Main hide configs

### PR DESCRIPTION
**Pull request by Simontwice**
# Description
when running tests, the auto generated config files pile up locally. If we place it in tmp, it does not happen.

# Checklist
Answer each question with "yes", and provide an explanation if the answer isn't what is expected.

1. Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - Answer: yes
2. Are all variables set with logical defaults that are backward compatible?
   - Answer: yes
3. Can you provide a link to a Neptune experiment verifying the functionality of this PR?
   - Answer: not applicable
4. Have you successfully executed the linter and tests?
   - Answer: yes
5. Are all functions concise and don't require splitting?
   - Answer: yes
6. Is there documentation for arguments and complex logic?
   - Answer: yes
7. Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - Answer: yes
8. Are all functions placed in appropriate files?
   - Answer: yes
9. Is the PR name meaningful and descriptive?
   - Answer: yes
10. Is PR description provided, or unnecessary?
    - Answer: yes
  
Other questions:

11. Have you not made changes to the requirements or anything related to the Singularity image? If you have, did you generate and upload a new image to the clusters?
    - Answer:
12. Is the change significant enough to notify all individuals working with this repository?
    - Answer:
13. Is there a need for a second reviewer?
    - Answer:

### CODE REVIEW

**Review by crewtool — CHANGES_REQUESTED** [review]
nope

**Comment by Simontwice** [comment]
> nope

I will need to to elaborate. This code is executed remotely, in the target directory that contains the code. Only one suite of experiments is executed there, each with their own config. @crewtool

**Comment by crewtool** [comment]
As I understand the way we want to pass branch name through writing it to `/tmp` (in another PR) I don't get why we want to write all experiments there. How about creating a folder with <experiment_name>_<date> inside ran_experiments folder (and add it to .gitignore) and put all configs there?

**Review by maciek-pioro — APPROVED** [review]

**Review by maciek-pioro — CHANGES_REQUESTED** [review]
unapprove

**Comment by Simontwice** [comment]
> As I understand the way we want to pass branch name through writing it to `/tmp` (in another PR) I don't get why we want to write all experiments there. How about creating a folder with <experiment_name>_ inside ran_experiments folder (and add it to .gitignore) and put all configs there?

We do not write any experiments locally. This happens in the remote directory. What you have locally is the actual configs you call your local script with. This final config is something that is specific to the specific experiment (if your grid involves 8 experiments there will be 8 configs), and is uploaded to neptune. I really, really do not see the point of keeping them locally as well, since the original is much more readable and contains full information.

**Review by crewtool — APPROVED** [review]
Ok, LGTM

**Review by maciek-pioro — APPROVED** [review]

**Pull request merged**
