### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by sebastianjaszczur**
# Description
Create license, and add license to readme.

AFAIK license applies globally then, there should be no need to add a license header to each and every file.

# Checklist
Answer each question with "yes", and provide an explanation if the answer isn't what is expected.

1. Is this PR focused on a single feature without the possibility of being divided into smaller PRs?
   - Answer: Y
2. Are all variables set with logical defaults that are backward compatible?
   - Answer: N/A
3. Can you provide a link to a Neptune experiment verifying the functionality of this PR?
   - Answer: N/A
4. Have you successfully executed the linter and tests?
   - Answer: N/A
5. Are all functions concise and don't require splitting?
   - Answer: N/A
6. Is there documentation for arguments and complex logic?
   - Answer: N/A
7. Are there no temporary solutions in the code? Should a task be added to Trello to refine the code?
   - Answer: N/A
8. Are all functions placed in appropriate files?
   - Answer: N/A
9. Is the PR name meaningful and descriptive?
   - Answer:  Yes
10. Is PR description provided, or unnecessary?
    - Answer: Yes
  
Other questions:

11. Have you not made changes to the requirements or anything related to the Singularity image? If you have, did you generate and upload a new image to the clusters?
    - Answer: No
12. Is the change significant enough to notify all individuals working with this repository?
    - Answer: Yes (to agree to this license)
13. Is there a need for a second reviewer?
    - Answer: No

### CODE REVIEW

**Comment by TomaszOdrzygozdz** [comment]
LGTM

**Review by ludziej — APPROVED** [review]
OK

**Review by crewtool — APPROVED** [review]
Not a lawyer, but lgtm

**Review by TomaszOdrzygozdz — APPROVED** [review]

**Comment by maciek-pioro** [comment]
LGTM

**Review by kuba-krj — APPROVED** [review]

**Review by Simontwice — APPROVED** [review]
Hewra

**Pull request merged**
